"""Fixed uniqueness

Revision ID: 10a0dc7d6058
Revises: 9a4d249bd8c4
Create Date: 2024-10-11 18:55:58.066504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a0dc7d6058'
down_revision = '9a4d249bd8c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint('question_answer1_key', type_='unique')
        batch_op.drop_constraint('question_answer2_key', type_='unique')
        batch_op.drop_constraint('question_answer3_key', type_='unique')
        batch_op.drop_constraint('question_logo_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_unique_constraint('question_logo_key', ['logo'])
        batch_op.create_unique_constraint('question_answer3_key', ['answer3'])
        batch_op.create_unique_constraint('question_answer2_key', ['answer2'])
        batch_op.create_unique_constraint('question_answer1_key', ['answer1'])

    # ### end Alembic commands ###
