"""empty message

Revision ID: 8aba909d225e
Revises: e23f2cb270ee
Create Date: 2025-01-22 12:56:33.051039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aba909d225e'
down_revision = 'e23f2cb270ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(length=240),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=240),
               existing_nullable=False)

    # ### end Alembic commands ###
